#!/usr/bin/bash
chmod +x ./setupdatabase ./starter ./start ./stop ./restart
mv fireworm.service /usr/lib/systemd/system/
systemctl enable fireworm.service
echo -n "configuring database..."
rm -f data.db
touch data.db
./setupdatabase
echo "done"
systemctl start fireworm
