#! /usr/bin/racket
#lang racket/base
(require "schedule.rkt"
          "configure.rkt"
          db/sqlite3
         )
(define(init-data-file! fi)
 (define cnn (sqlite3-connect #:database fi #:mode 'create))
 (init-sql! cnn))
 
(init-data-file! data-path)
