#! /usr/bin/racket
#lang racket
(require "schedule.rkt"
          db/sqlite3
         )
(define(init-data-file! fi)
 (define cnn (sqlite3-connect #:database fi))
 (init-sql! cnn))
 
(init-data-file! data-path)
