#! /usr/bin/racket
 #lang racket/base
(require web-server/servlet-env
         "main.rkt"
         )

(serve/servlet start
               #:port 80
               #:servlet-path "/weixin"
               #:listen-ip "0.0.0"
               #:command-line? #t)
